PrimeFaces.locales['tr'] = {
    closeText: 'kapat',
    prevText: 'geri',
    nextText: 'ileri',
    currentText: 'bugün',
    monthNames: ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],
    monthNamesShort: ['Oca','Şub','Mar','Nis','May','Haz', 'Tem','Ağu','Eyl','Eki','Kas','Ara'],
    dayNames: ['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'],
    dayNamesShort: ['Pz','Pt','Sa','Ça','Pe','Cu','Ct'],
    dayNamesMin: ['Pz','Pt','Sa','Ça','Pe','Cu','Ct'],
    weekHeader: 'Hf',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: '',
    timeOnlyTitle: 'Zaman Seçiniz',
    timeText: 'Zaman',
    hourText: 'Saat',
    minuteText: 'Dakika',
    secondText: 'Saniye',
    ampm: false,
    month: 'Ay',
    week: 'Hafta',
    day: 'Gün',
    allDayText : 'Tüm Gün',
    aria: {
        close: 'Kapat',
        prevYear: 'Önceki Yıl',
        nextYear: 'Sonraki Yıl',
        prevMonth: 'Önceki Ay',
        nextMonth: 'Sonraki Ay',
        prevDecade: 'Önceki On Yıl',
        nextDecade: 'Sonraki On Yıl',
        chooseMonth: 'Ay Seç',
        chooseYear: 'Yıl Seç',
        chooseDate: 'Tarih Seç',
        prevHour: 'Önceki Saat',
        nextHour: 'Sonraki Saat',
        prevMinute: 'Önceki Dakika',
        nextMinute: 'Sonraki Dakika',
        prevSecond: 'Önceki Saniye',
        nextSecond: 'Sonraki Saniye',
        am: 'ÖÖ',
        pm: 'ÖS'
    }
};

PrimeFaces.locales['de'] = {
    closeText: 'Schlie�en',
    prevText: 'Zur�ck',
    nextText: 'Weiter',
    monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    monthNamesShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
    dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    dayNamesShort: ['Son', 'Mon', 'Die', 'Mit', 'Don', 'Fre', 'Sam'],
    dayNamesMin: ['S', 'M', 'D', 'M ', 'D', 'F ', 'S'],
    weekHeader: 'Woche',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: '',
    timeOnlyTitle: 'Nur Zeit',
    timeText: 'Zeit',
    hourText: 'Stunde',
    minuteText: 'Minute',
    secondText: 'Sekunde',
    currentText: 'Aktuelles Datum',
    ampm: false,
    month: 'Monat',
    week: 'Woche',
    day: 'Tag',
    allDayText: 'Ganzer Tag',
    aria: {
        close: 'Schließen',
        prevYear: 'Vorheriges Jahr',
        nextYear: 'Nächstes Jahr',
        prevMonth: 'Vorheriger Monat',
        nextMonth: 'Nächster Monat',
        prevDecade: 'Vorheriges Jahrzehnt',
        nextDecade: 'Nächstes Jahrzehnt',
        chooseMonth: 'Monat wählen',
        chooseYear: 'Jahr wählen',
        chooseDate: 'Datum wählen',
        prevHour: 'Vorherige Stunde',
        nextHour: 'Nächste Stunde',
        prevMinute: 'Vorherige Minute',
        nextMinute: 'Nächste Minute',
        prevSecond: 'Vorherige Sekunde',
        nextSecond: 'Nächste Sekunde',
        am: 'Vormittag',
        pm: 'Nachmittag'
    }
};